/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torneos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Torneos */
        get: operations["listar_torneos_api_v1_torneos_get"];
        put?: never;
        /** Crear Torneo */
        post: operations["crear_torneo_api_v1_torneos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torneos/{torneo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Torneo */
        get: operations["obtener_torneo_api_v1_torneos__torneo_id__get"];
        put?: never;
        post?: never;
        /**
         * Dar De Baja Torneo
         * @description Borrado lógico (Estado='Inactivo'). No hay DELETE físico: ver el
         *     comentario sobre ON DELETE CASCADE en database/02_constraints.sql.
         */
        delete: operations["dar_de_baja_torneo_api_v1_torneos__torneo_id__delete"];
        options?: never;
        head?: never;
        /** Actualizar Torneo */
        patch: operations["actualizar_torneo_api_v1_torneos__torneo_id__patch"];
        trace?: never;
    };
    "/api/v1/equipos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Equipos */
        get: operations["listar_equipos_api_v1_equipos_get"];
        put?: never;
        /** Crear Equipo */
        post: operations["crear_equipo_api_v1_equipos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipos/{equipo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Equipo */
        get: operations["obtener_equipo_api_v1_equipos__equipo_id__get"];
        put?: never;
        post?: never;
        /** Dar De Baja Equipo */
        delete: operations["dar_de_baja_equipo_api_v1_equipos__equipo_id__delete"];
        options?: never;
        head?: never;
        /** Actualizar Equipo */
        patch: operations["actualizar_equipo_api_v1_equipos__equipo_id__patch"];
        trace?: never;
    };
    "/api/v1/jugadores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Jugadores */
        get: operations["listar_jugadores_api_v1_jugadores_get"];
        put?: never;
        /** Crear Jugador */
        post: operations["crear_jugador_api_v1_jugadores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jugadores/{jugador_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Jugador */
        get: operations["obtener_jugador_api_v1_jugadores__jugador_id__get"];
        put?: never;
        post?: never;
        /** Dar De Baja Jugador */
        delete: operations["dar_de_baja_jugador_api_v1_jugadores__jugador_id__delete"];
        options?: never;
        head?: never;
        /** Actualizar Jugador */
        patch: operations["actualizar_jugador_api_v1_jugadores__jugador_id__patch"];
        trace?: never;
    };
    "/api/v1/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Eventos */
        get: operations["listar_eventos_api_v1_eventos_get"];
        put?: never;
        /** Crear Evento */
        post: operations["crear_evento_api_v1_eventos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventos/{evento_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Evento */
        get: operations["obtener_evento_api_v1_eventos__evento_id__get"];
        put?: never;
        post?: never;
        /** Dar De Baja Evento */
        delete: operations["dar_de_baja_evento_api_v1_eventos__evento_id__delete"];
        options?: never;
        head?: never;
        /** Actualizar Evento */
        patch: operations["actualizar_evento_api_v1_eventos__evento_id__patch"];
        trace?: never;
    };
    "/api/v1/partidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Partidos
         * @description Público, sin auth (roles-3-modulos-plan.md, Fase 1: los resultados
         *     ya son públicos a propósito). `arbitro_id` (Fase 3, D1) es un filtro
         *     más, no un chequeo de permiso: PartidoOut ya expone arbitro_id en
         *     cada fila, así que este query param no agrega ninguna fuga nueva,
         *     solo evita filtrar del lado del cliente.
         */
        get: operations["listar_partidos_api_v1_partidos_get"];
        put?: never;
        /**
         * Crear Partido
         * @description Programa un partido. trg_partidos_validar_inscripcion (06_triggers.sql)
         *     rechaza si alguno de los dos equipos no está inscrito y no cancelado en
         *     el torneo — el error llega como 400 con el mensaje del trigger.
         *
         *     Árbitro NO tiene este endpoint (roles-3-modulos-plan.md, Fase 1, D4):
         *     crear partidos es de TorneoAdmin/AdminGeneral. Árbitro solo carga
         *     partidos que ya le asignaron.
         */
        post: operations["crear_partido_api_v1_partidos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partidos/{partido_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Partido */
        get: operations["obtener_partido_api_v1_partidos__partido_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancelar Partido
         * @description Borrado lógico -> Estado='Cancelado' (no 'Inactivo': no es un valor
         *     válido para partidos.estado, ver chk_partidos_estado).
         */
        delete: operations["cancelar_partido_api_v1_partidos__partido_id__delete"];
        options?: never;
        head?: never;
        /**
         * Actualizar Partido
         * @description Árbitro conserva este endpoint para avanzar el estado de SU partido
         *     (Programado -> En curso -> Finalizado). El chequeo de "¿es tuyo?" vive
         *     en PartidoService.update(), no acá (D5).
         */
        patch: operations["actualizar_partido_api_v1_partidos__partido_id__patch"];
        trace?: never;
    };
    "/api/v1/inscripciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Inscripciones */
        get: operations["listar_inscripciones_api_v1_inscripciones_get"];
        put?: never;
        /**
         * Inscribir Equipo
         * @description unique_inscripcion (02_constraints.sql) evita inscribir el mismo
         *     equipo dos veces en el mismo torneo (409).
         */
        post: operations["inscribir_equipo_api_v1_inscripciones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inscripciones/{inscripcion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Inscripcion */
        get: operations["obtener_inscripcion_api_v1_inscripciones__inscripcion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar Inscripcion
         * @description Cambiar a Estado='Cancelado' es el borrado lógico de una inscripción.
         */
        patch: operations["actualizar_inscripcion_api_v1_inscripciones__inscripcion_id__patch"];
        trace?: never;
    };
    "/api/v1/plantillas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Plantilla */
        get: operations["listar_plantilla_api_v1_plantillas_get"];
        put?: never;
        /**
         * Dar De Alta Jugador
         * @description dorsal único por equipo mientras la fila está vigente
         *     (uq_dorsal_por_equipo_vigente, 03_indexes.sql).
         */
        post: operations["dar_de_alta_jugador_api_v1_plantillas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plantillas/{vinculo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Vinculo */
        get: operations["obtener_vinculo_api_v1_plantillas__vinculo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar Vinculo */
        patch: operations["actualizar_vinculo_api_v1_plantillas__vinculo_id__patch"];
        trace?: never;
    };
    "/api/v1/plantillas/{vinculo_id}/baja": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dar De Baja Jugador
         * @description Cierra la vigencia (fecha_fin) y libera el dorsal para otro jugador.
         */
        post: operations["dar_de_baja_jugador_api_v1_plantillas__vinculo_id__baja_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventos-partido": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Eventos Partido */
        get: operations["listar_eventos_partido_api_v1_eventos_partido_get"];
        put?: never;
        /**
         * Registrar Evento Partido
         * @description fn_validar_jugador_partido (06_triggers.sql) rechaza si el equipo no
         *     disputa el partido, si el jugador no pertenecía a ese equipo en esa
         *     fecha, o si jugador_id_entra falta/sobra según el tipo de evento.
         *
         *     Árbitro: el chequeo de "¿es tu partido?" vive en
         *     EventoPartidoService.create() (D5), no acá.
         */
        post: operations["registrar_evento_partido_api_v1_eventos_partido_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventos-partido/{evento_partido_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Evento Partido */
        get: operations["obtener_evento_partido_api_v1_eventos_partido__evento_partido_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eventos-partido/{evento_partido_id}/anular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Anular Evento Partido
         * @description Estado='Anulado' para un evento cargado por error (ej: gol mal
         *     registrado). No se borra físicamente, se anula: mantiene el historial.
         *
         *     Árbitro: mismo chequeo que en registrar_evento_partido, ver
         *     EventoPartidoService.anular() (D5).
         */
        post: operations["anular_evento_partido_api_v1_eventos_partido__evento_partido_id__anular_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Usuarios */
        get: operations["listar_usuarios_api_v1_usuarios_get"];
        put?: never;
        /** Crear Usuario */
        post: operations["crear_usuario_api_v1_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/{usuario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Usuario */
        get: operations["obtener_usuario_api_v1_usuarios__usuario_id__get"];
        put?: never;
        post?: never;
        /**
         * Dar De Baja Usuario
         * @description Rechaza que un AdminGeneral se desactive a sí mismo — chequeo en
         *     UsuarioService.soft_delete() (T6).
         */
        delete: operations["dar_de_baja_usuario_api_v1_usuarios__usuario_id__delete"];
        options?: never;
        head?: never;
        /**
         * Actualizar Usuario
         * @description Rechaza que un AdminGeneral se cambie su propio rol o se desactive a
         *     sí mismo — chequeo en UsuarioService.update() (T6).
         */
        patch: operations["actualizar_usuario_api_v1_usuarios__usuario_id__patch"];
        trace?: never;
    };
    "/api/v1/estadisticas/torneos/{torneo_id}/posiciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tabla Posiciones */
        get: operations["tabla_posiciones_api_v1_estadisticas_torneos__torneo_id__posiciones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estadisticas/torneos/{torneo_id}/goleadores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Goleadores */
        get: operations["goleadores_api_v1_estadisticas_torneos__torneo_id__goleadores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estadisticas/torneos/{torneo_id}/resultados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resultados Partidos */
        get: operations["resultados_partidos_api_v1_estadisticas_torneos__torneo_id__resultados_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estadisticas/proximos-partidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proximos Partidos */
        get: operations["proximos_partidos_api_v1_estadisticas_proximos_partidos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/estadisticas/equipos/{equipo_id}/plantilla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plantilla Equipo */
        get: operations["plantilla_equipo_api_v1_estadisticas_equipos__equipo_id__plantilla_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** EquipoCreate */
        EquipoCreate: {
            /** Nombre */
            nombre: string;
        };
        /** EquipoOut */
        EquipoOut: {
            /** Nombre */
            nombre: string;
            /** Id */
            id: number;
            /**
             * Estado
             * @enum {string}
             */
            estado: "Activo" | "Inactivo";
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
            /**
             * Fecha Modificacion
             * Format: date-time
             */
            fecha_modificacion: string;
        };
        /** EquipoUpdate */
        EquipoUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Estado */
            estado?: ("Activo" | "Inactivo") | null;
        };
        /** EventoCreate */
        EventoCreate: {
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion?: string | null;
        };
        /** EventoOut */
        EventoOut: {
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion?: string | null;
            /** Id */
            id: number;
            /**
             * Estado
             * @enum {string}
             */
            estado: "Activo" | "Inactivo";
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
            /**
             * Fecha Modificacion
             * Format: date-time
             */
            fecha_modificacion: string;
        };
        /** EventoPartidoCreate */
        EventoPartidoCreate: {
            /** Partidos Id */
            partidos_id: number;
            /** Jugador Id */
            jugador_id: number;
            /** Equipo Id */
            equipo_id: number;
            /** Eventos Id */
            eventos_id: number;
            /** Jugador Id Entra */
            jugador_id_entra?: number | null;
            /** Minuto */
            minuto: number;
        };
        /** EventoPartidoOut */
        EventoPartidoOut: {
            /** Id */
            id: number;
            /** Partidos Id */
            partidos_id: number;
            /** Jugador Id */
            jugador_id: number;
            /** Equipo Id */
            equipo_id: number;
            /** Eventos Id */
            eventos_id: number;
            /** Jugador Id Entra */
            jugador_id_entra: number | null;
            /** Minuto */
            minuto: number;
            /**
             * Estado
             * @enum {string}
             */
            estado: "Registrado" | "Anulado";
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
            /**
             * Fecha Modificacion
             * Format: date-time
             */
            fecha_modificacion: string;
        };
        /** EventoUpdate */
        EventoUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Descripcion */
            descripcion?: string | null;
            /** Estado */
            estado?: ("Activo" | "Inactivo") | null;
        };
        /** GoleadorOut */
        GoleadorOut: {
            /** Torneo Id */
            torneo_id: number;
            /** Jugador Id */
            jugador_id: number;
            /** Jugador */
            jugador: string;
            /** Equipo Id */
            equipo_id: number;
            /** Equipo */
            equipo: string;
            /** Goles */
            goles: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InscripcionTorneoCreate */
        InscripcionTorneoCreate: {
            /** Torneo Id */
            torneo_id: number;
            /** Equipo Id */
            equipo_id: number;
        };
        /** InscripcionTorneoOut */
        InscripcionTorneoOut: {
            /** Id */
            id: number;
            /** Torneo Id */
            torneo_id: number;
            /** Equipo Id */
            equipo_id: number;
            /**
             * Estado
             * @enum {string}
             */
            estado: "Inscrito" | "Cancelado" | "Confirmado";
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
            /**
             * Fecha Modificacion
             * Format: date-time
             */
            fecha_modificacion: string;
        };
        /** InscripcionTorneoUpdate */
        InscripcionTorneoUpdate: {
            /**
             * Estado
             * @enum {string}
             */
            estado: "Inscrito" | "Cancelado" | "Confirmado";
        };
        /** JugadorCreate */
        JugadorCreate: {
            /** Nombre */
            nombre: string;
        };
        /** JugadorEquipoCreate */
        JugadorEquipoCreate: {
            /** Jugador Id */
            jugador_id: number;
            /** Equipo Id */
            equipo_id: number;
            /** Dorsal */
            dorsal?: number | null;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
        };
        /** JugadorEquipoOut */
        JugadorEquipoOut: {
            /** Id */
            id: number;
            /** Jugador Id */
            jugador_id: number;
            /** Equipo Id */
            equipo_id: number;
            /** Dorsal */
            dorsal: number | null;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /** Fecha Fin */
            fecha_fin: string | null;
            /**
             * Estado
             * @enum {string}
             */
            estado: "Activo" | "Inactivo" | "Suspendido";
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
            /**
             * Fecha Modificacion
             * Format: date-time
             */
            fecha_modificacion: string;
        };
        /** JugadorEquipoUpdate */
        JugadorEquipoUpdate: {
            /** Dorsal */
            dorsal?: number | null;
            /** Fecha Fin */
            fecha_fin?: string | null;
            /** Estado */
            estado?: ("Activo" | "Inactivo" | "Suspendido") | null;
        };
        /** JugadorOut */
        JugadorOut: {
            /** Nombre */
            nombre: string;
            /** Id */
            id: number;
            /**
             * Estado
             * @enum {string}
             */
            estado: "Activo" | "Inactivo";
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
            /**
             * Fecha Modificacion
             * Format: date-time
             */
            fecha_modificacion: string;
        };
        /** JugadorUpdate */
        JugadorUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Estado */
            estado?: ("Activo" | "Inactivo") | null;
        };
        /** PartidoCreate */
        PartidoCreate: {
            /** Torneo Id */
            torneo_id: number;
            /** Equipos Id Local */
            equipos_id_local: number;
            /** Equipos Id Visitante */
            equipos_id_visitante: number;
            /**
             * Fecha Partido
             * Format: date-time
             */
            fecha_partido: string;
            /** Jornada */
            jornada?: number | null;
            /**
             * Fase
             * @default Regular
             * @enum {string}
             */
            fase: "Regular" | "Grupos" | "Octavos" | "Cuartos" | "Semifinal" | "Final" | "Tercer puesto";
            /** Grupo */
            grupo?: string | null;
        };
        /** PartidoOut */
        PartidoOut: {
            /** Torneo Id */
            torneo_id: number;
            /** Equipos Id Local */
            equipos_id_local: number;
            /** Equipos Id Visitante */
            equipos_id_visitante: number;
            /**
             * Fecha Partido
             * Format: date-time
             */
            fecha_partido: string;
            /** Jornada */
            jornada?: number | null;
            /**
             * Fase
             * @default Regular
             * @enum {string}
             */
            fase: "Regular" | "Grupos" | "Octavos" | "Cuartos" | "Semifinal" | "Final" | "Tercer puesto";
            /** Grupo */
            grupo?: string | null;
            /** Id */
            id: number;
            /**
             * Estado
             * @enum {string}
             */
            estado: "Programado" | "En curso" | "Finalizado" | "Cancelado";
            /** Arbitro Id */
            arbitro_id: number | null;
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
            /**
             * Fecha Modificacion
             * Format: date-time
             */
            fecha_modificacion: string;
        };
        /** PartidoUpdate */
        PartidoUpdate: {
            /** Fecha Partido */
            fecha_partido?: string | null;
            /** Jornada */
            jornada?: number | null;
            /** Fase */
            fase?: ("Regular" | "Grupos" | "Octavos" | "Cuartos" | "Semifinal" | "Final" | "Tercer puesto") | null;
            /** Grupo */
            grupo?: string | null;
            /** Estado */
            estado?: ("Programado" | "En curso" | "Finalizado" | "Cancelado") | null;
            /** Arbitro Id */
            arbitro_id?: number | null;
        };
        /** PlantillaJugadorOut */
        PlantillaJugadorOut: {
            /** Equipo Id */
            equipo_id: number;
            /** Equipo */
            equipo: string;
            /** Jugador Id */
            jugador_id: number;
            /** Jugador */
            jugador: string;
            /** Dorsal */
            dorsal: number | null;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
        };
        /** PosicionOut */
        PosicionOut: {
            /** Torneo Id */
            torneo_id: number;
            /** Equipo Id */
            equipo_id: number;
            /** Equipo */
            equipo: string;
            /** Pj */
            pj: number;
            /** Pg */
            pg: number;
            /** Pe */
            pe: number;
            /** Pp */
            pp: number;
            /** Gf */
            gf: number;
            /** Gc */
            gc: number;
            /** Dg */
            dg: number;
            /** Pts */
            pts: number;
        };
        /** ProximoPartidoOut */
        ProximoPartidoOut: {
            /** Partido Id */
            partido_id: number;
            /** Torneo Id */
            torneo_id: number;
            /** Torneo */
            torneo: string;
            /** Equipo Local Id */
            equipo_local_id: number;
            /** Equipo Local */
            equipo_local: string;
            /** Equipo Visitante Id */
            equipo_visitante_id: number;
            /** Equipo Visitante */
            equipo_visitante: string;
            /**
             * Fecha Partido
             * Format: date-time
             */
            fecha_partido: string;
            /** Jornada */
            jornada: number | null;
            /** Fase */
            fase: string;
            /** Grupo */
            grupo: string | null;
            /** Estado */
            estado: string;
        };
        /** ResultadoPartidoOut */
        ResultadoPartidoOut: {
            /** Partido Id */
            partido_id: number;
            /** Torneo Id */
            torneo_id: number;
            /** Equipo Local Id */
            equipo_local_id: number;
            /** Equipo Local */
            equipo_local: string;
            /** Equipo Visitante Id */
            equipo_visitante_id: number;
            /** Equipo Visitante */
            equipo_visitante: string;
            /** Goles Local */
            goles_local: number;
            /** Goles Visitante */
            goles_visitante: number;
            /**
             * Fecha Partido
             * Format: date-time
             */
            fecha_partido: string;
            /** Jornada */
            jornada: number | null;
            /** Fase */
            fase: string;
            /** Grupo */
            grupo: string | null;
            /** Estado */
            estado: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Rol */
            rol: string;
        };
        /** TorneoCreate */
        TorneoCreate: {
            /** Nombre */
            nombre: string;
            /** Disciplina */
            disciplina: string;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
        };
        /** TorneoOut */
        TorneoOut: {
            /** Nombre */
            nombre: string;
            /** Disciplina */
            disciplina: string;
            /**
             * Fecha Inicio
             * Format: date
             */
            fecha_inicio: string;
            /**
             * Fecha Fin
             * Format: date
             */
            fecha_fin: string;
            /** Id */
            id: number;
            /**
             * Estado
             * @enum {string}
             */
            estado: "Activo" | "Inactivo" | "Finalizado";
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
            /**
             * Fecha Modificacion
             * Format: date-time
             */
            fecha_modificacion: string;
        };
        /** TorneoUpdate */
        TorneoUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Disciplina */
            disciplina?: string | null;
            /** Fecha Inicio */
            fecha_inicio?: string | null;
            /** Fecha Fin */
            fecha_fin?: string | null;
            /** Estado */
            estado?: ("Activo" | "Inactivo" | "Finalizado") | null;
        };
        /** UsuarioCreate */
        UsuarioCreate: {
            /** Username */
            username: string;
            /** Nombre */
            nombre: string;
            /** Password */
            password: string;
            /**
             * Rol
             * @default Publico
             * @enum {string}
             */
            rol: "AdminGeneral" | "TorneoAdmin" | "Arbitro" | "Publico";
        };
        /** UsuarioOut */
        UsuarioOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Nombre */
            nombre: string;
            /**
             * Rol
             * @enum {string}
             */
            rol: "AdminGeneral" | "TorneoAdmin" | "Arbitro" | "Publico";
            /**
             * Estado
             * @enum {string}
             */
            estado: "Activo" | "Inactivo";
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
            /**
             * Fecha Modificacion
             * Format: date-time
             */
            fecha_modificacion: string;
        };
        /** UsuarioUpdate */
        UsuarioUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Rol */
            rol?: ("AdminGeneral" | "TorneoAdmin" | "Arbitro" | "Publico") | null;
            /** Estado */
            estado?: ("Activo" | "Inactivo") | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"];
                };
            };
        };
    };
    listar_torneos_api_v1_torneos_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                estado?: ("Activo" | "Inactivo" | "Finalizado") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorneoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_torneo_api_v1_torneos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorneoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorneoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_torneo_api_v1_torneos__torneo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                torneo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorneoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dar_de_baja_torneo_api_v1_torneos__torneo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                torneo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorneoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_torneo_api_v1_torneos__torneo_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                torneo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorneoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorneoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_equipos_api_v1_equipos_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                estado?: ("Activo" | "Inactivo") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_equipo_api_v1_equipos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_equipo_api_v1_equipos__equipo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dar_de_baja_equipo_api_v1_equipos__equipo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_equipo_api_v1_equipos__equipo_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquipoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_jugadores_api_v1_jugadores_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                estado?: ("Activo" | "Inactivo") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JugadorOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_jugador_api_v1_jugadores_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JugadorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JugadorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_jugador_api_v1_jugadores__jugador_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jugador_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JugadorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dar_de_baja_jugador_api_v1_jugadores__jugador_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jugador_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JugadorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_jugador_api_v1_jugadores__jugador_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jugador_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JugadorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JugadorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_eventos_api_v1_eventos_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                estado?: ("Activo" | "Inactivo") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_evento_api_v1_eventos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_evento_api_v1_eventos__evento_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evento_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dar_de_baja_evento_api_v1_eventos__evento_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evento_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_evento_api_v1_eventos__evento_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evento_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_partidos_api_v1_partidos_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                torneo_id?: number | null;
                estado?: ("Programado" | "En curso" | "Finalizado" | "Cancelado") | null;
                arbitro_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartidoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_partido_api_v1_partidos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartidoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_partido_api_v1_partidos__partido_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partido_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelar_partido_api_v1_partidos__partido_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partido_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_partido_api_v1_partidos__partido_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partido_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartidoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_inscripciones_api_v1_inscripciones_get: {
        parameters: {
            query?: {
                torneo_id?: number | null;
                equipo_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InscripcionTorneoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inscribir_equipo_api_v1_inscripciones_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InscripcionTorneoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InscripcionTorneoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_inscripcion_api_v1_inscripciones__inscripcion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inscripcion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InscripcionTorneoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_inscripcion_api_v1_inscripciones__inscripcion_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inscripcion_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InscripcionTorneoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InscripcionTorneoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_plantilla_api_v1_plantillas_get: {
        parameters: {
            query?: {
                equipo_id?: number | null;
                jugador_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JugadorEquipoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dar_de_alta_jugador_api_v1_plantillas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JugadorEquipoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JugadorEquipoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_vinculo_api_v1_plantillas__vinculo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vinculo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JugadorEquipoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_vinculo_api_v1_plantillas__vinculo_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vinculo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JugadorEquipoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JugadorEquipoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dar_de_baja_jugador_api_v1_plantillas__vinculo_id__baja_post: {
        parameters: {
            query: {
                fecha_fin: string;
            };
            header?: never;
            path: {
                vinculo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JugadorEquipoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_eventos_partido_api_v1_eventos_partido_get: {
        parameters: {
            query?: {
                partidos_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoPartidoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_evento_partido_api_v1_eventos_partido_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventoPartidoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoPartidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_evento_partido_api_v1_eventos_partido__evento_partido_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evento_partido_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoPartidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anular_evento_partido_api_v1_eventos_partido__evento_partido_id__anular_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evento_partido_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoPartidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_usuarios_api_v1_usuarios_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                rol?: ("AdminGeneral" | "TorneoAdmin" | "Arbitro" | "Publico") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_usuario_api_v1_usuarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_usuario_api_v1_usuarios__usuario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dar_de_baja_usuario_api_v1_usuarios__usuario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_usuario_api_v1_usuarios__usuario_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                usuario_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tabla_posiciones_api_v1_estadisticas_torneos__torneo_id__posiciones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                torneo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosicionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    goleadores_api_v1_estadisticas_torneos__torneo_id__goleadores_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                torneo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoleadorOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resultados_partidos_api_v1_estadisticas_torneos__torneo_id__resultados_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                torneo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoPartidoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proximos_partidos_api_v1_estadisticas_proximos_partidos_get: {
        parameters: {
            query?: {
                torneo_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProximoPartidoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plantilla_equipo_api_v1_estadisticas_equipos__equipo_id__plantilla_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlantillaJugadorOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
